In [3]:
libraries: They are collection of modules and functions to perform specific tasks.

pandas: data manipulation
Numpy(Numerical python): multi-dimentional arrays
                         and mathematical operations
matplotlib,seaborn,plotly: data visualisation
statistics:
sklearn (scikit learn): machine learning
keras: deep learning
tensorflow: google
pytorch: facebook

SyntaxError: invalid syntax (2792018650.py, line 1)

In [8]:
import pandas as pd

In [9]:
d1 = pd.read_excel("emp_data.xlsx")

In [10]:
d1

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [ ]:
pandas
* series: 1D data called as series
* dataframe: 2D data called as DataFrame

In [11]:
pd.Series([1,2,4,5,6,89])

0     1
1     2
2     4
3     5
4     6
5    89
dtype: int64

In [16]:
d2 = pd.read_csv("mtcars.csv")

In [13]:
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
Basic stuff we perform after loading the data:(Initial Analysis)
1) loaded the data 
2) size of the data 
3) column
4) datatypes
5) null values
6) duplicates
7) rename the column

In [17]:
d3 = pd.read_csv("studata.txt")

In [18]:
d3

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [20]:
d4 = pd.read_table("chipotle.tsv")

''' or d4 = pd.read_csv("chipotle.tsv", sep = "\t")'''

' or d4 = pd.read_csv("chipotle.tsv", sep = "\t")'

In [21]:
d4

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [22]:
d5 = pd.read_csv("chipotle.tsv", sep = "\t")
d5

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [90]:
d5.shape

(4622, 5)

In [23]:
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [24]:
d2.shape #32 rows and 12 columns

(32, 12)

In [25]:
d2.shape[0] #accessing row count

32

In [26]:
d2.shape[1] #accessing column count

12

In [27]:
# see only column names
d2.columns

Index(['manufacturer', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [28]:
#check datatypes
d2.dtypes

manufacturer     object
mpg             float64
cyl               int64
disp            float64
hp                int64
drat            float64
wt              float64
qsec            float64
vs                int64
am                int64
gear              int64
carb              int64
dtype: object

In [29]:
#checking null values
d2.isna().sum() #adding all the null values(if you don't write this it'll show true for false which is difficult to identify

manufacturer    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
vs              0
am              0
gear            0
carb            0
dtype: int64

In [30]:
#checking duplicates
d2.duplicated().sum() #adding all the duplicate values(if you don't write this it'll show true for false which is difficult to identify

np.int64(0)

In [31]:
temp = d2.head() #will give you first five records(tail will give you last 5 records)
temp

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [32]:
d2 = pd.concat([d2,temp],ignore_index=True)
# if not added ignore index it'll repeat the row numbers 
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
33,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
34,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
35,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
36,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [33]:
d2.duplicated().sum()

np.int64(5)

In [34]:
#checking the duplicated values
d2[d2.duplicated()]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
33,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
34,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
35,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
36,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [35]:
#dropping the duplicates
d2.drop_duplicates(inplace=True) # adding (inplace=True) for permanent delition or it'll be deleated in a temparery format

In [36]:
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [37]:
#Renaming the column
d2.rename({'manufacturer':'brand'},axis = 1) #addind axis = 1 to perform on column, add 0 to perform on row

,brand,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [38]:
#adding a column
d2["qsec sq"] = d2["qsec"]**2
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,270.9316
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,289.6804
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,346.3321
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,250.9056
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,400.0000
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,524.4100
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,334.8900
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,357.2100
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,302.7600
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,309.7600
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,324.0000
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,323.2804
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,317.5524
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,303.4564
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,379.0809
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,342.9904
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,396.0100
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,400.4001
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,284.5969
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,299.2900
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,237.4681
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,290.7025
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,357.2100
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,278.8900
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,285.6100
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,240.2500
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,213.1600
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,345.9600

In [39]:
d2['disp'] = d2['disp']-5
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
0,Mazda RX4,21.0,6,155.0,110,3.90,2.620,16.46,0,1,4,4,270.9316
1,Mazda RX4 Wag,21.0,6,155.0,110,3.90,2.875,17.02,0,1,4,4,289.6804
2,Datsun 710,22.8,4,103.0,93,3.85,2.320,18.61,1,1,4,1,346.3321
3,Hornet 4 Drive,21.4,6,253.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
6,Duster 360,14.3,8,355.0,245,3.21,3.570,15.84,0,0,3,4,250.9056
7,Merc 240D,24.4,4,141.7,62,3.69,3.190,20.00,1,0,4,2,400.0000
8,Merc 230,22.8,4,135.8,95,3.92,3.150,22.90,1,0,4,2,524.4100
9,Merc 280,19.2,6,162.6,123,3.92,3.440,18.30,1,0,4,4,334.8900
10,Merc 280C,17.8,6,162.6,123,3.92,3.440,18.90,1,0,4,4,357.2100
11,Merc 450SE,16.4,8,270.8,180,3.07,4.070,17.40,0,0,3,3,302.7600
12,Merc 450SL,17.3,8,270.8,180,3.07,3.730,17.60,0,0,3,3,309.7600
13,Merc 450SLC,15.2,8,270.8,180,3.07,3.780,18.00,0,0,3,3,324.0000
14,Cadillac Fleetwood,10.4,8,467.0,205,2.93,5.250,17.98,0,0,3,4,323.2804
15,Lincoln Continental,10.4,8,455.0,215,3.00,5.424,17.82,0,0,3,4,317.5524
16,Chrysler Imperial,14.7,8,435.0,230,3.23,5.345,17.42,0,0,3,4,303.4564
17,Fiat 128,32.4,4,73.7,66,4.08,2.200,19.47,1,1,4,1,379.0809
18,Honda Civic,30.4,4,70.7,52,4.93,1.615,18.52,1,1,4,2,342.9904
19,Toyota Corolla,33.9,4,66.1,65,4.22,1.835,19.90,1,1,4,1,396.0100
20,Toyota Corona,21.5,4,115.1,97,3.70,2.465,20.01,1,0,3,1,400.4001
21,Dodge Challenger,15.5,8,313.0,150,2.76,3.520,16.87,0,0,3,2,284.5969
22,AMC Javelin,15.2,8,299.0,150,3.15,3.435,17.30,0,0,3,2,299.2900
23,Camaro Z28,13.3,8,345.0,245,3.73,3.840,15.41,0,0,3,4,237.4681
24,Pontiac Firebird,19.2,8,395.0,175,3.08,3.845,17.05,0,0,3,2,290.7025
25,Fiat X1-9,27.3,4,74.0,66,4.08,1.935,18.90,1,1,4,1,357.2100
26,Porsche 914-2,26.0,4,115.3,91,4.43,2.140,16.70,0,1,5,2,278.8900
27,Lotus Europa,30.4,4,90.1,113,3.77,1.513,16.90,1,1,5,2,285.6100
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
29,Ferrari Dino,19.7,6,140.0,175,3.62,2.770,15.50,0,1,5,6,240.2500
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600
31,Volvo 142E,21.4,4,116.0,109,4.11,2.780,18.60,1,1,4,2,345.9600

In [92]:
d2.drop(columns = ['qsec sq'],inplace = True)

KeyError: "['qsec sq'] not found in axis"

In [ ]:
del d2['qsec sq'] #use del for permanent deleate

In [41]:
# how to access rows and columns
d2["manufacturer"] #series format

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [42]:
d2.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [43]:
#accessing it in dataframe format
d2[['manufacturer']]

           manufacturer
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [44]:
#accessing multiple columns
d2.mpg,cyl,disp

NameError: name 'cyl' is not defined

In [45]:
d2['mpg','cyl','disp']

KeyError: ('mpg', 'cyl', 'disp')

In [47]:
d2[['mpg','cyl','disp']]

     mpg  cyl   disp
0   21.0    6  155.0
1   21.0    6  155.0
2   22.8    4  103.0
3   21.4    6  253.0
4   18.7    8  355.0
5   18.1    6  220.0
6   14.3    8  355.0
7   24.4    4  141.7
8   22.8    4  135.8
9   19.2    6  162.6
10  17.8    6  162.6
11  16.4    8  270.8
12  17.3    8  270.8
13  15.2    8  270.8
14  10.4    8  467.0
15  10.4    8  455.0
16  14.7    8  435.0
17  32.4    4   73.7
18  30.4    4   70.7
19  33.9    4   66.1
20  21.5    4  115.1
21  15.5    8  313.0
22  15.2    8  299.0
23  13.3    8  345.0
24  19.2    8  395.0
25  27.3    4   74.0
26  26.0    4  115.3
27  30.4    4   90.1
28  15.8    8  346.0
29  19.7    6  140.0
30  15.0    8  296.0
31  21.4    4  116.0

In [ ]:
there are two methods to extract particular rows and columns 
1) iloc: index locator
2) loc: name locator

In [ ]:
syntax:
var.iloc[row_stv:row_spv:row_ss,col_stv:col_spv:col_ss]
default stv: 0
        spv: upto
        ss: 1

In [48]:
# 1st 5 row and 1st 5 col
d2.iloc[0:5:1,0:5:1]

        manufacturer   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  155.0  110
1      Mazda RX4 Wag  21.0    6  155.0  110
2         Datsun 710  22.8    4  103.0   93
3     Hornet 4 Drive  21.4    6  253.0  110
4  Hornet Sportabout  18.7    8  355.0  175

In [51]:
# all rows with last 5 columns

d2.iloc[0:32:1,-5:]

    vs  am  gear  carb   qsec sq
0    0   1     4     4  270.9316
1    0   1     4     4  289.6804
2    1   1     4     1  346.3321
3    1   0     3     1  377.9136
4    0   0     3     2  289.6804
5    1   0     3     1  408.8484
6    0   0     3     4  250.9056
7    1   0     4     2  400.0000
8    1   0     4     2  524.4100
9    1   0     4     4  334.8900
10   1   0     4     4  357.2100
11   0   0     3     3  302.7600
12   0   0     3     3  309.7600
13   0   0     3     3  324.0000
14   0   0     3     4  323.2804
15   0   0     3     4  317.5524
16   0   0     3     4  303.4564
17   1   1     4     1  379.0809
18   1   1     4     2  342.9904
19   1   1     4     1  396.0100
20   1   0     3     1  400.4001
21   0   0     3     2  284.5969
22   0   0     3     2  299.2900
23   0   0     3     4  237.4681
24   0   0     3     2  290.7025
25   1   1     4     1  357.2100
26   0   1     5     2  278.8900
27   1   1     5     2  285.6100
28   0   1     5     4  210.2500
29   0   1     5     6  240.2500
30   0   1     5     8  213.1600
31   1   1     4     2  345.9600

In [52]:
# even index rows odd index columns
d2.iloc[0::2,1::2]

     mpg   disp  drat   qsec  am  carb
0   21.0  155.0  3.90  16.46   1     4
2   22.8  103.0  3.85  18.61   1     1
4   18.7  355.0  3.15  17.02   0     2
6   14.3  355.0  3.21  15.84   0     4
8   22.8  135.8  3.92  22.90   0     2
10  17.8  162.6  3.92  18.90   0     4
12  17.3  270.8  3.07  17.60   0     3
14  10.4  467.0  2.93  17.98   0     4
16  14.7  435.0  3.23  17.42   0     4
18  30.4   70.7  4.93  18.52   1     2
20  21.5  115.1  3.70  20.01   0     1
22  15.2  299.0  3.15  17.30   0     2
24  19.2  395.0  3.08  17.05   0     2
26  26.0  115.3  4.43  16.70   1     2
28  15.8  346.0  4.22  14.50   1     4
30  15.0  296.0  3.54  14.60   1     8

In [ ]:
#accessing random rows and columns
rows: 2,5,8,13,17,25
col: 1,4,6

In [53]:
d2.iloc[[2,5,8,13,17,25],[1,4,6]]

     mpg   hp     wt
2   22.8   93  2.320
5   18.1  105  3.460
8   22.8   95  3.150
13  15.2  180  3.780
17  32.4   66  2.200
25  27.3   66  1.935

In [54]:
d2.loc[0:5] #here 0,5 is considered as name and not index (row name and index are same but column name and index are diffrent)

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
0,Mazda RX4,21.0,6,155.0,110,3.90,2.620,16.46,0,1,4,4,270.9316
1,Mazda RX4 Wag,21.0,6,155.0,110,3.90,2.875,17.02,0,1,4,4,289.6804
2,Datsun 710,22.8,4,103.0,93,3.85,2.320,18.61,1,1,4,1,346.3321
3,Hornet 4 Drive,21.4,6,253.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484

In [60]:
d2.loc[22:,'cyl':'qsec']

    cyl   disp   hp  drat     wt   qsec
22    8  299.0  150  3.15  3.435  17.30
23    8  345.0  245  3.73  3.840  15.41
24    8  395.0  175  3.08  3.845  17.05
25    4   74.0   66  4.08  1.935  18.90
26    4  115.3   91  4.43  2.140  16.70
27    4   90.1  113  3.77  1.513  16.90
28    8  346.0  264  4.22  3.170  14.50
29    6  140.0  175  3.62  2.770  15.50
30    8  296.0  335  3.54  3.570  14.60
31    4  116.0  109  4.11  2.780  18.60

In [ ]:
rows: 1,2,11,12,21,22,31
col: mpg,wt,am,crd

In [62]:
d2.loc[[1,2,11,12,21,22,31],['mpg','wt','am','carb']]

     mpg     wt  am  carb
1   21.0  2.875   1     4
2   22.8  2.320   1     1
11  16.4  4.070   0     3
12  17.3  3.730   0     3
21  15.5  3.520   0     2
22  15.2  3.435   0     2
31  21.4  2.780   1     2

In [63]:
#extract the records of 8 cylinder
d2[d2['cyl']==8]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
6,Duster 360,14.3,8,355.0,245,3.21,3.570,15.84,0,0,3,4,250.9056
11,Merc 450SE,16.4,8,270.8,180,3.07,4.070,17.40,0,0,3,3,302.7600
12,Merc 450SL,17.3,8,270.8,180,3.07,3.730,17.60,0,0,3,3,309.7600
13,Merc 450SLC,15.2,8,270.8,180,3.07,3.780,18.00,0,0,3,3,324.0000
14,Cadillac Fleetwood,10.4,8,467.0,205,2.93,5.250,17.98,0,0,3,4,323.2804
15,Lincoln Continental,10.4,8,455.0,215,3.00,5.424,17.82,0,0,3,4,317.5524
16,Chrysler Imperial,14.7,8,435.0,230,3.23,5.345,17.42,0,0,3,4,303.4564
21,Dodge Challenger,15.5,8,313.0,150,2.76,3.520,16.87,0,0,3,2,284.5969
22,AMC Javelin,15.2,8,299.0,150,3.15,3.435,17.30,0,0,3,2,299.2900
23,Camaro Z28,13.3,8,345.0,245,3.73,3.840,15.41,0,0,3,4,237.4681
24,Pontiac Firebird,19.2,8,395.0,175,3.08,3.845,17.05,0,0,3,2,290.7025
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600

In [67]:
#extract the record whos disp range is 200 to 400

d2[(d2['disp']>=200) & (d2['disp']<=400)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
3,Hornet 4 Drive,21.4,6,253.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
6,Duster 360,14.3,8,355.0,245,3.21,3.570,15.84,0,0,3,4,250.9056
11,Merc 450SE,16.4,8,270.8,180,3.07,4.070,17.40,0,0,3,3,302.7600
12,Merc 450SL,17.3,8,270.8,180,3.07,3.730,17.60,0,0,3,3,309.7600
13,Merc 450SLC,15.2,8,270.8,180,3.07,3.780,18.00,0,0,3,3,324.0000
21,Dodge Challenger,15.5,8,313.0,150,2.76,3.520,16.87,0,0,3,2,284.5969
22,AMC Javelin,15.2,8,299.0,150,3.15,3.435,17.30,0,0,3,2,299.2900
23,Camaro Z28,13.3,8,345.0,245,3.73,3.840,15.41,0,0,3,4,237.4681
24,Pontiac Firebird,19.2,8,395.0,175,3.08,3.845,17.05,0,0,3,2,290.7025
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600

In [68]:
d2[d2['disp'].between(200,400)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
3,Hornet 4 Drive,21.4,6,253.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
6,Duster 360,14.3,8,355.0,245,3.21,3.570,15.84,0,0,3,4,250.9056
11,Merc 450SE,16.4,8,270.8,180,3.07,4.070,17.40,0,0,3,3,302.7600
12,Merc 450SL,17.3,8,270.8,180,3.07,3.730,17.60,0,0,3,3,309.7600
13,Merc 450SLC,15.2,8,270.8,180,3.07,3.780,18.00,0,0,3,3,324.0000
21,Dodge Challenger,15.5,8,313.0,150,2.76,3.520,16.87,0,0,3,2,284.5969
22,AMC Javelin,15.2,8,299.0,150,3.15,3.435,17.30,0,0,3,2,299.2900
23,Camaro Z28,13.3,8,345.0,245,3.73,3.840,15.41,0,0,3,4,237.4681
24,Pontiac Firebird,19.2,8,395.0,175,3.08,3.845,17.05,0,0,3,2,290.7025
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600

In [72]:
# extract the records either mpg>20 or gear 5
d2[(d2['mpg']>20) | (d2['gear']==5)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
0,Mazda RX4,21.0,6,155.0,110,3.90,2.620,16.46,0,1,4,4,270.9316
1,Mazda RX4 Wag,21.0,6,155.0,110,3.90,2.875,17.02,0,1,4,4,289.6804
2,Datsun 710,22.8,4,103.0,93,3.85,2.320,18.61,1,1,4,1,346.3321
3,Hornet 4 Drive,21.4,6,253.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
7,Merc 240D,24.4,4,141.7,62,3.69,3.190,20.00,1,0,4,2,400.0000
8,Merc 230,22.8,4,135.8,95,3.92,3.150,22.90,1,0,4,2,524.4100
17,Fiat 128,32.4,4,73.7,66,4.08,2.200,19.47,1,1,4,1,379.0809
18,Honda Civic,30.4,4,70.7,52,4.93,1.615,18.52,1,1,4,2,342.9904
19,Toyota Corolla,33.9,4,66.1,65,4.22,1.835,19.90,1,1,4,1,396.0100
20,Toyota Corona,21.5,4,115.1,97,3.70,2.465,20.01,1,0,3,1,400.4001
25,Fiat X1-9,27.3,4,74.0,66,4.08,1.935,18.90,1,1,4,1,357.2100
26,Porsche 914-2,26.0,4,115.3,91,4.43,2.140,16.70,0,1,5,2,278.8900
27,Lotus Europa,30.4,4,90.1,113,3.77,1.513,16.90,1,1,5,2,285.6100
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
29,Ferrari Dino,19.7,6,140.0,175,3.62,2.770,15.50,0,1,5,6,240.2500
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600
31,Volvo 142E,21.4,4,116.0,109,4.11,2.780,18.60,1,1,4,2,345.9600

In [76]:
#extract the records whos qsec range is not in 15 to 20
d2[(d2['qsec']<15) | (d2['qsec']>20)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
8,Merc 230,22.8,4,135.8,95,3.92,3.150,22.90,1,0,4,2,524.4100
20,Toyota Corona,21.5,4,115.1,97,3.70,2.465,20.01,1,0,3,1,400.4001
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.50,0,1,5,4,210.2500
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600

In [80]:
# extract 1st 10 records 
# last 5 records 
# random 10 records 

d2.head(10) #just using head() will give you first 5 records

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
0,Mazda RX4,21.0,6,155.0,110,3.90,2.620,16.46,0,1,4,4,270.9316
1,Mazda RX4 Wag,21.0,6,155.0,110,3.90,2.875,17.02,0,1,4,4,289.6804
2,Datsun 710,22.8,4,103.0,93,3.85,2.320,18.61,1,1,4,1,346.3321
3,Hornet 4 Drive,21.4,6,253.0,110,3.08,3.215,19.44,1,0,3,1,377.9136
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
6,Duster 360,14.3,8,355.0,245,3.21,3.570,15.84,0,0,3,4,250.9056
7,Merc 240D,24.4,4,141.7,62,3.69,3.190,20.00,1,0,4,2,400.0000
8,Merc 230,22.8,4,135.8,95,3.92,3.150,22.90,1,0,4,2,524.4100
9,Merc 280,19.2,6,162.6,123,3.92,3.440,18.30,1,0,4,4,334.8900

In [81]:
d2.tail() #tail() gives you the last 5 records

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
27,Lotus Europa,30.4,4,90.1,113,3.77,1.513,16.9,1,1,5,2,285.61
28,Ford Pantera L,15.8,8,346.0,264,4.22,3.170,14.5,0,1,5,4,210.25
29,Ferrari Dino,19.7,6,140.0,175,3.62,2.770,15.5,0,1,5,6,240.25
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.6,0,1,5,8,213.16
31,Volvo 142E,21.4,4,116.0,109,4.11,2.780,18.6,1,1,4,2,345.96

In [84]:
d2.sample(10) #sample() gives you random data

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec sq
4,Hornet Sportabout,18.7,8,355.0,175,3.15,3.440,17.02,0,0,3,2,289.6804
31,Volvo 142E,21.4,4,116.0,109,4.11,2.780,18.60,1,1,4,2,345.9600
20,Toyota Corona,21.5,4,115.1,97,3.70,2.465,20.01,1,0,3,1,400.4001
13,Merc 450SLC,15.2,8,270.8,180,3.07,3.780,18.00,0,0,3,3,324.0000
21,Dodge Challenger,15.5,8,313.0,150,2.76,3.520,16.87,0,0,3,2,284.5969
0,Mazda RX4,21.0,6,155.0,110,3.90,2.620,16.46,0,1,4,4,270.9316
5,Valiant,18.1,6,220.0,105,2.76,3.460,20.22,1,0,3,1,408.8484
30,Maserati Bora,15.0,8,296.0,335,3.54,3.570,14.60,0,1,5,8,213.1600
24,Pontiac Firebird,19.2,8,395.0,175,3.08,3.845,17.05,0,0,3,2,290.7025
22,AMC Javelin,15.2,8,299.0,150,3.15,3.435,17.30,0,0,3,2,299.2900

In [87]:
#calculate minimum, maximum,average of wt
d2['wt'].min()

1.513

In [88]:
d2['wt'].max()

5.424

In [89]:
d2['wt'].mean()

np.float64(3.2172500000000004)

In [ ]:
# Assignment
on insurance data
1) each region wise total expenses
2) gender wise avg bmi and expenses
3) each region,each children and smoker class wise total expenses

use: group by and pivot table

In [93]:
ins = pd.read_csv("insurance.csv")

In [94]:
ins

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [95]:
ins.groupby(by ="region")['expenses'].sum().sort_values(ascending=False)

region
southeast    5363689.80
northeast    4343668.64
northwest    4035711.93
southwest    4012754.82
Name: expenses, dtype: float64

In [97]:
ins.groupby(by="sex")[['bmi','expenses']].mean().round(2) #using round() to round off decimal

          bmi  expenses
sex
female  30.38  12569.58
male    30.95  13956.75

In [100]:
ins.groupby(by = ['region','children','smoker'])['expenses'].sum()

region     children  smoker
northeast  0         no         976747.39
                     yes        732342.66
           1         no         544403.10
                     yes        711482.80
           2         no         490110.44
                     yes        204262.33
           3         no         221947.50
                     yes        340039.14
           4         no         101396.36
           5         no          20936.92
northwest  0         no         814816.76
                     yes        680000.21
           1         no         518805.68
                     yes        238233.23
           2         no         547296.76
                     yes        341347.99
           3         no         348081.14
                     yes        470082.25
           4         no          46609.63
                     yes         21472.48
           5         no           8965.80
southeast  0         no         826029.55
                     yes       1420619.78
           1         no         585202.76
                     yes        715066.23
           2         no         360936.28
                     yes        677142.84
           3         no         287678.69
                     yes        358065.90
           4         no          72255.12
           5         no          60692.65
southwest  0         no         876219.52
                     yes        771294.22
           1         no         535306.23
                     yes        276399.64
           2         no         357878.89
                     yes        638679.83
           3         no         276805.98
                     yes        108084.41
           4         no          46408.47
                     yes         58124.36
           5         no          48530.01
                     yes         19023.26
Name: expenses, dtype: float64

In [101]:
ins.groupby(by = ['region','children','smoker'])['expenses'].mean()

region     children  smoker
northeast  0         no         8072.292479
                     yes       28167.025385
           1         no         9898.238182
                     yes       32340.127273
           2         no        11669.296190
                     yes       22695.814444
           3         no         7653.362069
                     yes       34003.914000
           4         no        14485.194286
           5         no         6978.973333
northwest  0         no         7544.599630
                     yes       28333.342083
           1         no         7981.625846
                     yes       26470.358889
           2         no         9950.850182
                     yes       31031.635455
           3         no        10547.913333
                     yes       36160.173077
           4         no         9321.926000
                     yes       21472.480000
           5         no         8965.800000
southeast  0         no         7060.081624
                     yes       35515.494500
           1         no         8016.476164
                     yes       32503.010455
           2         no         7519.505833
                     yes       37619.046667
           3         no        11986.612083
                     yes       32551.445455
           4         no        14451.024000
           5         no        10115.441667
southwest  0         no         7754.155044
                     yes       30851.768800
           1         no         7647.231857
                     yes       34549.955000
           2         no         8946.972250
                     yes       37569.401765
           3         no         8650.186875
                     yes       21616.882000
           4         no         9281.694000
                     yes       29062.180000
           5         no         6932.858571
                     yes       19023.260000
Name: expenses, dtype: float64

In [104]:
pd.pivot_table(data=ins,values='expenses',index='region',columns=['smoker','children'],aggfunc='mean').round(2)

smoker          no                                                        yes  \
children         0        1         2         3         4         5         0
region
northeast  8072.29  9898.24  11669.30   7653.36  14485.19   6978.97  28167.03
northwest  7544.60  7981.63   9950.85  10547.91   9321.93   8965.80  28333.34
southeast  7060.08  8016.48   7519.51  11986.61  14451.02  10115.44  35515.49
southwest  7754.16  7647.23   8946.97   8650.19   9281.69   6932.86  30851.77

smoker
children          1         2         3         4         5
region
northeast  32340.13  22695.81  34003.91       NaN       NaN
northwest  26470.36  31031.64  36160.17  21472.48       NaN
southeast  32503.01  37619.05  32551.45       NaN       NaN
southwest  34549.96  37569.40  21616.88  29062.18  19023.26

In [109]:
st1=pd.read_csv("Sales Transactions-2017.csv")

In [110]:
st2=pd.read_csv("Sales Transactions-2018.csv")

In [111]:
st3=pd.read_csv("Sales Transactions-2019.csv")

In [112]:
st1

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [113]:
st2

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [114]:
st3

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [118]:
sales = pd.concat([st1,st2,st3],ignore_index=True)

In [119]:
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [ ]:
#Perform initial analysis on the above table

In [120]:
sales.shape #checking no of rows and columns

(111206, 9)

In [121]:
sales.columns #checking column names

Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate', 'Gross', 'Disc',
       'Voucher Amount'],
      dtype='object')

In [122]:
sales.info() #understanding datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111206 entries, 0 to 111205
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            98615 non-null   object
 1   Voucher         98649 non-null   object
 2   Party           111166 non-null  object
 3   Product         98615 non-null   object
 4   Qty             98649 non-null   object
 5   Rate            98648 non-null   object
 6   Gross           98648 non-null   object
 7   Disc            5597 non-null    object
 8   Voucher Amount  27560 non-null   object
dtypes: object(9)
memory usage: 7.6+ MB

In [123]:
sales.isnull().sum() #checking missing values

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [124]:
sales = sales.dropna(how="all") #Removes rows where every column is NaN

In [125]:
sales.describe()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

In [130]:
sales['Party'].value_counts().head(10) #Top 10 customers

Party
TP13                  13056
K.SRIHARI              2537
KPR                    2354
SVP-BUCHHI             1620
HAMPI FOODS            1419
BSR                    1413
Kvkc                   1346
GANESHMESS             1324
Srinu                  1322
BRHAMADEVI SUDHEER     1289
Name: count, dtype: int64

In [131]:
sales.groupby('Product')['Qty'].sum().sort_values(ascending = False).head(10) #Top selling products

Product
80 Leaf                9922999182319999101099999291018991929192092181...
SMITH 4*5 POLY         9393121503123123133123121031225312104010312939...
KRISHNA 10*12 RED      9301,200.003001,200.003003003003003001,200.003...
PINK PLATES 8"         9010304040404040104080120120120402004040404040...
TIRUMALA-50B(10*12)    9001030030010030030030015030300300100300800300...
NAPKEENS 27*27         8888140160888888176888888881088108888888888888...
90leaf                                                           8881699
14 MULTI(8PACK)                                                      880
ASHA 10*12 BLU                                       8401,260.0084042060
BUISCUT COX-1000ML                                                   825
Name: Qty, dtype: object

In [135]:
int(sales[('Gross')]).sum()

TypeError: cannot convert the series to <class 'int'>

In [137]:
sales.groupby("Party")["Gross"].sum().sort_values(ascending=False).head(10)

TypeError: '<' not supported between instances of 'str' and 'int'

In [138]:
sales.groupby('Party')['Gross'].sum().sort_values(ascending=False).head(10)

TypeError: '<' not supported between instances of 'str' and 'int'